version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - static-code-analysis:
          context:
            - docker-hub-creds-ro
      - test-3.7:
          context:
            - docker-hub-creds-ro
      - test-3.8:
          context:
            - docker-hub-creds-ro
      - test-3.9:
          context:
            - docker-hub-creds-ro

defaults: &defaults
  working_directory: ~/code
  environment:
    STRICT_WARNINGS: '1'
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: |
        pip install -r requirements_tests.txt
  - run:
      name: Test
      command: PYTHONPATH=. pytest

jobs:
  static-code-analysis:
    <<: *defaults
    docker:
    - image: cimg/python:3.8
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements_lint.txt

      - run:
          name: Lint
          when: always
          command: |
            lintlizard

  test-3.7:
    <<: *defaults
    docker:
    - image: cimg/python:3.7
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    - image: redis:3.2.12-alpine
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  test-3.8:
    <<: *defaults
    docker:
    - image: cimg/python:3.8
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    - image: redis:3.2.12-alpine
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  test-3.9:
    <<: *defaults
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      - image: redis:3.2.12-alpine
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
