version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.6:
          context:
            - docker-hub-creds-ro
      - test-3.7:
          context:
            - docker-hub-creds-ro
      - test-3.8:
          context:
            - docker-hub-creds-ro

defaults: &defaults
  working_directory: ~/code
  environment:
    STRICT_WARNINGS: '1'
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: |
        sudo pip install -r requirements.txt
        sudo pip install -r requirements_tests.txt
  - run:
      name: Lint
      command: flake8
  - run:
      name: Test
      command: PYTHONPATH=. pytest

jobs:
  test-3.6:
    <<: *defaults
    docker:
    - image: circleci/python:3.6
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    - image: redis:3.2.12-alpine
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  test-3.7:
    <<: *defaults
    docker:
    - image: circleci/python:3.7
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    - image: redis:3.2.12-alpine
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  test-3.8:
    <<: *defaults
    docker:
    - image: circleci/python:3.8
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    - image: redis:3.2.12-alpine
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
