name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  STRICT_WARNINGS: "1"
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements_lint.txt
      - name: Run linting
        run: lintlizard
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    services:
      redis:
        image: redis:3.2.12-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements_tests.txt
      - name: Run tests
        run: |
          PYTHONPATH=. pytest
